import json,pathlib,html
ROOT=pathlib.Path(__file__).parent;OUT=ROOT/'docs';projects=json.loads((ROOT/'projects.json').read_text());esc=html.escape
A=lambda f:'/assets/'+f
favicon="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='white'/%3E%3Ctext x='9' y='48' font-family='Georgia' font-size='46' fill='%23bc461d'%3Ef%3C/text%3E%3C/svg%3E"
def head(title,desc):return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} — Folco Soffietti</title><meta name="description" content="{esc(desc,quote=True)}"><meta name="theme-color" content="#ffffff"><link rel="icon" href="{favicon}"><link rel="stylesheet" href="/style.css"><script src="/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Folco Soffietti, home">Folco<span> S.</span></a><p class="header-note">Design, research & the making of things</p><nav class="top-nav" aria-label="Main navigation"><a href="/#work">Work</a><a href="/#about">About</a><a href="/#contact">Contact</a></nav></header>'''
def cursor():return '''<div class="hand-cursor" aria-hidden="true"><img class="open" src="/assets/hand-open.webp" alt=""><img class="closed" src="/assets/hand-closed.webp" alt=""><span></span></div>'''
def foot():return '''<footer class="contact wrap" id="contact"><div class="contact-top"><p class="eyebrow">Have something in mind?</p><img class="contact-hand" src="/assets/hand-open.webp" alt="" loading="lazy"></div><h2 class="reveal">Let’s make<br><em>something matter.</em></h2><a class="email" href="mailto:folco.soffietti@gmail.com" data-cursor="Say hello">folco.soffietti@gmail.com</a><div class="contact-bottom"><span>© Folco Soffietti · Design & art</span><span>We can talk in English, italiano or français.</span><a href="#" class="text-link">Back to top ↑</a></div></footer>'''+cursor()+'''</body></html>'''
def url(p):return '/work/'+p['slug']+'/'
def row(p):return f'''<a class="project-row" href="{url(p)}" data-image="{A(p['cover'])}" data-title="{esc(p.get('short',p['title']),quote=True)}" data-kind="{esc(p['kind'],quote=True)}" data-dark="{str(p.get('dark',False)).lower()}" data-cursor="View work"><img class="mobile-project-image" src="{A(p['cover'])}" alt="{esc(p['title'])}" loading="lazy"><div><h3>{esc(p.get('short',p['title']))}</h3><small>{esc(p['kind'])}</small></div><span class="arr" aria-hidden="true">↗</span></a>'''
home=head('Design & art','An artisan’s approach to information design, illustration and sculpture. The portfolio of Folco Soffietti.')+'''<main id="main"><section class="hero wrap"><h1 class="name reveal">Folco <span class="surname">Soffietti</span></h1><div class="hero-main"><div class="hero-copy"><h2 class="reveal">A narrative <em>artisan.</em></h2></div><nav class="orbit" aria-label="Explore my practice"><div class="landscape-drag" tabindex="0" role="group" aria-label="Move the landscape with the arrow keys. Press Home to reset." data-cursor="Grab"><img class="orbit-image" src="/assets/landscape.webp" alt="My hand-drawn landscape, with a path connecting the surrounding buildings" fetchpriority="high" draggable="false"></div><a class="o1" href="#information"><span>01 / MAKING SENSE</span>Information<br>Design</a><a class="o2" href="#creative"><span>02 / TELLING STORIES</span>Creative<br>Design</a><a class="o3" href="#personal"><span>03 / KEEPING CURIOUS</span>Personal<br>practice</a></nav><div class="landscape-controls"><span>Pick up the landscape and move it.</span><button type="button" data-reset-landscape>Reset position ↺</button></div></div><div class="hero-foot"><span>RESEARCH INFORMS. HANDS EXPLORE.</span><a class="down" href="#about">SCROLL TO EXPLORE <i aria-hidden="true">↓</i></a></div></section><section class="about wrap" id="about"><p class="eyebrow">A way of working</p><div class="about-text"><p class="statement reveal">Different tools.<br>The same attention to <em>what matters.</em></p><div class="about-detail"><p>I think of myself as a narrative artisan. Whether creating a diagram, a digital interface, a graphic novel or a sculpture, the medium follows the questions and the story they trigger.</p><p>My research experience at Università Iuav di Venezia shapes an approach grounded in careful observation, clear communication and a willingness to experiment.</p></div></div></section><section class="wrap" id="work"><div class="work-heading"><h2 class="reveal">Selected <em>work.</em></h2><p class="eyebrow">Three connected practices / 01—03</p></div><div class="work-layout"><aside class="shared-view" aria-label="Project preview"><a href="/work/medigreen/" id="preview-link" data-cursor="View work"><div class="image-stage"><img src="/assets/posters-02.webp" alt="MEDIGREEN campaign poster" class="active"><img alt=""></div></a><div class="image-caption"><span id="preview-title">MEDIGREEN</span><span id="preview-kind">Visual identity</span></div></aside><div class="chapters">'''
sections=[('information','01','Information Design','Making complex subjects legible and appealing is what motivates my work in information design, data visualisation and visual identities across science, marine sustainability and European projects.','doodle-01.webp'),('creative','02','Creative Design','There is always a story behind. Illustration and comics are great media for bringing scientific and technological subjects closer, through characters, images and a little imagination.','fish.webp'),('personal','03','Personal practice','Making to learn and find balance. Sculpture is an ongoing exploration of material, gesture and form, with room for uncertainty and the pleasure of working by hand. A medium that can be integrated into communication when needed.','posture-study.webp')]
for id,num,title,desc,doodle in sections:
 home+=f'<section class="chapter" id="{id}"><p class="chapter-num">({num})</p><h2 class="reveal">{title}</h2><p class="desc">{desc}</p><div class="project-list">'+''.join(row(p) for p in projects if p['category']==title)+f'</div><div class="sketch-box sketch-{id}" aria-hidden="true"><img class="chapter-doodle" src="{A(doodle)}" alt="" loading="lazy"></div></section>'
home+='''</div></div></section><section class="playground" aria-labelledby="gallery-title"><div class="playground-title wrap"><div><p class="eyebrow">A few things from the workbench</p><h2 class="reveal" id="gallery-title">Follow your <em>curiosity.</em></h2></div><div class="gallery-controls"><span class="small">Explore</span><button data-gallery-prev aria-label="Previous artworks">←</button><button data-gallery-next aria-label="Next artworks">→</button></div></div><div class="drag-gallery" tabindex="0" role="region" aria-label="Draggable artwork gallery. Use arrow keys or the previous and next buttons." data-cursor="Grab"><div class="gallery-track">'''
items=[('plastissea','plastissea-17.webp','An underwater story','Illustration'),('sketchbook','doodle-10.webp','Notes in the margins','Drawing'),('medigreen','posters-06.webp','Many uses, one sea','Communication'),('sculpture','diana-4.webp','Learning to look','Sculpture'),('idee','idee-03.webp','Ideas in sequence','Comics'),('mediterranean-in-numbers','numbers-02.webp','Making scale visible','Data'),('sketchbook','doodle-06.webp','A place on paper','Sketchbook')]
for slug,img,title,kind in items:home+=f'<a class="gallery-item" href="/work/{slug}/" data-cursor="Grab / open" draggable="false"><figure><img src="{A(img)}" alt="{esc(title)}" loading="lazy" draggable="false"><figcaption>{title}<span>{kind}</span></figcaption></figure></a>'
home+='</div></div><p class="gallery-hint wrap">Drag to explore, use the arrows, or open a work to take a closer look.</p></section></main>'+foot();(OUT/'index.html').write_text(home)
for n,p in enumerate(projects):
 category_id=next(s[0] for s in sections if s[2]==p['category'])
 content=head(p['title'],p['description'])+f'''<main id="main"><section class="project-head wrap"><div class="breadcrumb"><a href="/#{category_id}">← {esc(p['category'])}</a><span>{n+1:02d} / {len(projects):02d}</span></div><h1 class="reveal">{esc(p['title'])}</h1><div class="project-intro"><dl class="project-meta"><div><dt>Practice</dt><dd>{esc(p['kind'])}</dd></div></dl><div><p class="project-description reveal">{esc(p['description'])}</p><p class="project-note">{esc(p['note'])}</p>'''

 content+='</div></div></section><section class="project-gallery wrap" aria-label="Project images">'
 if p['slug']=='aquaculture':
  content += '<div class="embedded-project wide"><iframe src="https://fsoff.github.io/Aquaculture-fr/" title="Filière Aquacole: explore the stages of the aquaculture sector" loading="eager" referrerpolicy="strict-origin-when-cross-origin"></iframe></div>'
 if p['slug']=='sculpture':
  content += '<div class="model-section wide"><h2>Resting Diana <em>(Maria)</em></h2><div class="model-viewer" data-model-viewer data-cursor="Rotate" tabindex="0" role="group" aria-label="Interactive sculpture. Use arrow keys to rotate and plus or minus to zoom."><img class="model-fallback" src="/assets/diana-4.webp" alt="Resting Diana, static view"><p class="model-status" role="status">Loading the sculpture…</p></div><div class="model-controls"><button data-model-left aria-label="Rotate sculpture left">← Rotate</button><button data-model-right aria-label="Rotate sculpture right">Rotate →</button><button data-model-zoom-in aria-label="Zoom in">+</button><button data-model-zoom-out aria-label="Zoom out">−</button><button data-model-reset>Reset view ↺</button></div><p class="viewer-hint">Drag to turn. Scroll or pinch to zoom. You can also use the buttons or keyboard.</p></div><script type="module" src="/sculpture.js"></script>'
 if p['slug']=='clay-study':
  frames=[A(f'turntable-{i:02d}.webp') for i in range(1,17)]
  content+=f'''<div class="turntable-section wide"><div class="turntable" data-turntable data-frames='{json.dumps(frames)}' data-cursor="Turn" tabindex="0" role="group" aria-label="Photographic sculpture turntable. Drag horizontally or use the arrow keys."><img src="{frames[0]}" alt="Clay sculpture, view 1 of 16" draggable="false"></div><div class="turntable-controls"><button data-turn-prev aria-label="Previous sculpture view">←</button><label>Turn the sculpture<input type="range" min="0" max="15" value="0" step="1" data-turn-range aria-label="Sculpture viewing angle"></label><button data-turn-next aria-label="Next sculpture view">→</button><span data-turn-count role="status">01 / 16</span></div><p class="viewer-hint">Drag horizontally to move through 16 studio photographs.</p></div>'''

 for i,item in enumerate(p['images']):
  file,cap=item[:2];cl=item[2] if len(item)>2 else ''
  content+=f'<figure class="{cl}"><button class="image-open" aria-label="Enlarge: {esc(cap,quote=True)}" data-cursor="Enlarge"><img src="{A(file)}" alt="{esc(cap,quote=True)}" loading="{"eager" if i==0 else "lazy"}"></button><figcaption>{esc(cap)}</figcaption></figure>'
 if 'video'in p:content+=f'<figure class="wide"><video class="project-video" controls playsinline preload="none" poster="/assets/film-poster.webp" aria-label="Drawing in motion"><source src="{A(p["video"])}" type="video/mp4">Your browser does not support video. <a href="{A(p["video"])}">Open the film</a>.</video><figcaption>Drawing in motion. A moving exploration of the supplied artwork.</figcaption></figure>'
 if 'reader'in p:
  r=p['reader'];pages=[A(f'{r["prefix"]}-{i:02d}.webp') for i in range(1,r['count']+1)]
  content+=f'''<div class="reader" data-reader data-pages='{json.dumps(pages)}' data-title="{esc(p['title'],quote=True)}" tabindex="0" aria-label="{esc(r['title'])}"><h2 style="font-size:40px;margin:35px 0 25px">{esc(r['title'])}</h2><div class="reader-toolbar"><button data-prev aria-label="Previous page">← Previous</button><span class="reader-progress" role="status" aria-live="polite">01 / {r['count']}</span><button data-next aria-label="Next page">Next →</button></div><img src="{pages[0]}" alt="{esc(p['title'])}, page 1" loading="lazy"><p class="reader-help">Use the buttons or the left and right arrow keys to turn the pages.</p></div>'''
 np=projects[(n+1)%len(projects)]
 content+=f'</section><section class="next-project wrap"><p class="eyebrow">Keep exploring / {esc(np["category"])}</p><a href="{url(np)}">{esc(np["title"])} ↗</a></section></main><dialog class="lightbox" aria-label="Enlarged artwork"><button class="close-lightbox" autofocus>Close ×</button><img alt=""><p class="lightbox-caption"></p></dialog>'+foot()
 folder=OUT/'work'/p['slug'];folder.mkdir(parents=True,exist_ok=True);(folder/'index.html').write_text(content)
(OUT/'404.html').write_text(head('Page not found','Return to the portfolio of Folco Soffietti.')+'<main class="notfound" id="main"><p class="eyebrow">404</p><h1>A loose page.</h1><p>This page could not be found.</p><a class="project-action" href="/">Return to the portfolio →</a></main>'+foot())
print('Built home,',len(projects),'project pages and 404.')

# Keep assets and navigation portable for GitHub Pages project repositories.
import re
for page in OUT.rglob('*.html'):
 depth=len(page.relative_to(OUT).parts)-1
 prefix='../'*depth if depth else './'
 text=page.read_text()
 text=re.sub(r'(["\'])/(?!/)',lambda m:m.group(1)+prefix,text)
 page.write_text(text)
